### ISSUE TITLE
Can drag elements over static end cards

### ISSUE THREAD

**Issue by solanin** [Fractionators/sugarizer#2]
You can move orange cards to left and right of purple ones.

This means that you can drag things before the "0" card and after the "1" card. This should not be allowed.

**Comment by bxs9775** [comment]
Could we take the "0" and "1" cards out of the &lt;ol&gt;?

edit: fixed the &lt;ol&gt;

**Comment by solanin** [comment]
Fixed: https://github.com/Fractionators/sugarizer/commit/e7979d57bb3373253a340c783bf814b30e62f6b9

**Comment by bxs9775** [comment]
If there are concerns about the state of my fix. We can reopen this.
